name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Install .NET SDK 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Build and Run Blazor App
      run: |
        dotnet build BlazorApp/BlazorApp.csproj
        nohup dotnet run --project BlazorApp/BlazorApp.csproj > blazor.log 2>&1 &

    - name: Wait for Blazor App to be ready and capture URL
      id: blazor-url
      run: |
        echo "Waiting for Blazor app to start..."
        MAX_WAIT=900
        TIME_WAITED=0
        URL=""
        while [ -z "$URL" ]; do
          URL=$(grep -Eo 'http://localhost:[0-9]+' blazor.log | head -1)
          if [ "$TIME_WAITED" -ge "$MAX_WAIT" ]; then
            echo "Blazor app failed to start within ${MAX_WAIT} seconds."
            exit 1
          fi
          echo "Waiting for Blazor app at ${URL}... (${TIME_WAITED}s/${MAX_WAIT}s)"
          sleep 5
          TIME_WAITED=$((TIME_WAITED + 5))
        done
        echo "Blazor app is running at $URL"
        echo "URL=$URL" >> $GITHUB_ENV

    - name: Verify Blazor App Process
      run: |
        echo "Verifying that Blazor App is running..."
        pgrep -lf "dotnet run --project BlazorApp/BlazorApp.csproj" || echo "Blazor app process is not running."
        ps aux | grep dotnet
        netstat -tuln | grep -Eo ':[0-9]+' || echo "No process is listening on any expected port."

    - name: Run Playwright tests
      run: |
        echo "Running Playwright tests on ${{ env.URL }}"
        npx playwright test --retries=2 --timeout=120000 --base-url=${{ env.URL }}

    - name: Output Blazor App Logs (on failure)
      if: failure()
      run: cat blazor.log

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
