name: Playwright Tests for Blazor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET Core for Blazor WebAssembly
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  # Use .NET 8.0 as per your project file

      # Step 3: Install Node.js (required for Playwright)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Compatible Node.js version

      # Step 4: Install Playwright dependencies
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Step 5: Restore .NET dependencies
      - name: Restore .NET dependencies
        run: dotnet restore

      # Step 6: Build the Blazor project
      - name: Build the Blazor project
        run: dotnet build --configuration Release

      # Step 7: Start Blazor WebAssembly app
      - name: Start Blazor WebAssembly app
        run: |
          nohup dotnet run --project BlazorApp/BlazorApp.csproj --urls http://localhost:5128 > /dev/null 2>&1 &
        timeout-minutes: 3

      # Step 8: Wait for Blazor WebAssembly app to be available
      - name: Wait for Blazor WebAssembly app to be available
        run: |
          timeout 60 sh -c 'until curl -sSf http://localhost:5128; do sleep 5; done'

      # Step 9: Print confirmation that the app is running and print the URL
      - name: Print App URL
        run: |
          echo "Blazor WebAssembly app is running at: http://localhost:5128"

      # Step 10: Install Playwright Browsers (Again, if needed for parallelization)
      - name: Install Playwright browsers again (if required for parallelization)
        run: npx playwright install --with-deps

      # Step 11: Run Playwright tests with single worker for stability
      - name: Run Playwright tests
        run: |
          npx playwright test --config=playwright.config.js
        env:
          CI: true

      # Step 12: Upload Playwright test results (Optional)
      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-results
          path: playwright-report/

      # Step 13: Upload Playwright HTML report (Optional)
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
