name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Install .NET SDK 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Check for port 5128 usage
      run: |
        if lsof -i :5128; then
          echo "Port 5128 is in use, cannot start the app."
          exit 1
        fi

    - name: Build and Run Blazor App
      run: |
        dotnet build BlazorApp/BlazorApp.csproj
        nohup dotnet run --project BlazorApp/BlazorApp.csproj --urls "http://localhost:5128" > blazor.log 2>&1 &

    - name: Wait for Blazor App to be ready
      run: |
        echo "Waiting for Blazor app to start..."
        MAX_WAIT=600  # Increased to 10 minutes
        TIME_WAITED=0
        while ! curl --output /dev/null --silent --head --fail http://localhost:5128; do
          echo "Waiting for Blazor app at http://localhost:5128... (${TIME_WAITED}s/${MAX_WAIT}s)"
          sleep 5
          TIME_WAITED=$((TIME_WAITED + 5))
          if [ "$TIME_WAITED" -ge "$MAX_WAIT" ]; then
            echo "Blazor app failed to start within ${MAX_WAIT} seconds."
            exit 1
          fi
        done
        echo "Blazor app is up and running at http://localhost:5128"

    - name: Verify Blazor App Process
      run: |
        if ! pgrep -f "dotnet run --project BlazorApp/BlazorApp.csproj"; then
          echo "Blazor app process is not running."
          exit 1
        fi

    - name: Verify Blazor App is accessible
      run: curl --fail http://localhost:5128 || exit 1

    - name: Run Playwright tests
      run: npx playwright test --timeout=120000

    - name: Output Blazor App Logs
      if: failure()
      run: cat blazor.log

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
