name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      web:
        image: mcr.microsoft.com/dotnet/aspnet:7.0
        ports:
          - 5128:80
        options: >-
          --health-cmd "curl --fail http://localhost:80/ || exit 1"
          --health-interval 30s  # Increased to 30 seconds
          --health-timeout 20s   # Increased to 20 seconds
          --health-retries 10    # Increased retries

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build and Start the Application
        run: |
          dotnet build
          dotnet run --urls=http://localhost:5128 &
          sleep 30  # Increased sleep time to ensure the app is fully started

      - name: Get container logs (for debugging)
        run: docker logs $(docker ps -q --filter ancestor=mcr.microsoft.com/dotnet/aspnet:7.0) || true

      - name: Run Playwright tests
        run: npx playwright test --timeout=60000  # Increased timeout to avoid timeout errors

      - name: Upload test artifacts (screenshots, videos)
        if: failure()  # Only upload if the tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: playwright-report
