name: Playwright Tests for Blazor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox]  # Only run tests for Chromium and Firefox

    steps:
      # Cache .NET packages
      - name: Cache .NET packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      # Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET Core for Blazor WebAssembly
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      # Step 3: Set up Node.js (required for Playwright)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 4: Install Node.js dependencies
      - name: Install Node.js dependencies (including Playwright)
        run: npm ci

      # Step 5: Install TypeScript globally
      - name: Install TypeScript
        run: npm install typescript --global

      # Step 6: Restore .NET dependencies
      - name: Restore .NET dependencies
        run: dotnet restore

      # Step 7: Build the Blazor project (No restore)
      - name: Build the Blazor project
        run: dotnet build --configuration Release --no-restore

      # Step 8: Start Blazor WebAssembly app in the background
      - name: Start Blazor WebAssembly app
        run: |
          nohup dotnet run --project BlazorApp/BlazorApp.csproj --urls http://localhost:5128 > app.log 2>&1 &
        timeout-minutes: 2

      # Step 9: Wait for Blazor WebAssembly app to be available
      - name: Wait for Blazor WebAssembly app to be available
        run: |
          echo "Waiting for Blazor WebAssembly app to be available..."
          for i in {1..20}; do
            curl --silent --fail http://localhost:5128 && break
            echo "Waiting for the server... retry $i"
            sleep 3
          done
          curl --silent --fail http://localhost:5128 || (echo "Server not available, failing build." && exit 1)

      # Step 10: Run Playwright tests
      - name: Run Playwright tests on ${{ matrix.browser }}
        run: npx playwright test --project=${{ matrix.browser }}

      # Step 11: Upload Playwright test results (optional)
      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: playwright-report/
