name: Playwright Tests for Blazor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox]  # Parallelize across browsers

    steps:
      # Step 1: Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 2: Cache .NET dependencies
      - name: Cache .NET packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      # Step 3: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 4: Set up Node.js (for Playwright)
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*  # Use latest LTS Node.js version

      # Step 5: Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm ci

      # Step 6: Set up .NET Core for Blazor WebAssembly
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      # Step 7: Restore .NET dependencies
      - name: Restore .NET dependencies
        run: dotnet restore

      # Step 8: Build the Blazor project
      - name: Build the Blazor project
        run: dotnet build --configuration Release

      # Step 9: Start Blazor WebAssembly app in the background
      - name: Start Blazor WebAssembly app
        run: |
          nohup dotnet run --project BlazorApp/BlazorApp.csproj --urls http://localhost:5128 > app.log 2>&1 &
        timeout-minutes: 3

      # Step 10: Wait for Blazor WebAssembly app to be available
      - name: Wait for Blazor WebAssembly app to be available
        run: |
          echo "Waiting for Blazor WebAssembly app to be available..."
          for i in {1..10}; do
            curl --silent --fail http://localhost:5128 && break
            echo "Waiting for the server... retry $i"
            sleep 6
          done
          curl --silent --fail http://localhost:5128 || (echo "Server not available, failing build." && exit 1)

      # Step 11: Run Playwright tests
      - name: Run Playwright tests on ${{ matrix.browser }}
        run: npx playwright test --project=${{ matrix.browser }}

      # Step 12: Upload Playwright test report (optional)
      - name: Upload Playwright test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
