name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Node.js (for Playwright)
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*  # Use latest LTS Node.js version

    # Step 3: Install dependencies (Node.js)
    - name: Install dependencies
      run: npm ci

    # Step 4: Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Step 5: Set up .NET Core for Blazor WebAssembly
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Set the correct version based on your project

    # Step 6: Restore .NET dependencies
    - name: Restore .NET dependencies
      run: dotnet restore

    # Step 7: Build the Blazor project
    - name: Build the Blazor project
      run: dotnet build --configuration Release

    # Step 8: Start Blazor WebAssembly app in the background
    - name: Start Blazor WebAssembly app
      run: |
        nohup dotnet run --project BlazorApp/BlazorApp.csproj --urls http://localhost:5128 > app.log 2>&1 &
      timeout-minutes: 3

    # Step 9: Wait for Blazor WebAssembly app to be available
    - name: Wait for Blazor WebAssembly app to be available
      run: |
        echo "Waiting for Blazor WebAssembly app to be available..."
        for i in {1..10}; do
          curl --silent --fail http://localhost:5128 && break
          echo "Waiting for the server... retry $i"
          sleep 6
        done
        curl --silent --fail http://localhost:5128 || (echo "Server not available, failing build." && exit 1)
    # Step 10: Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test

    # Step 11: Upload Playwright test report (optional)
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
