name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      web:
        image: mcr.microsoft.com/dotnet/aspnet:7.0
        ports:
          - 5128:80
        options: >-
          --health-cmd "curl --fail http://localhost:80/ || exit 1"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start the Application
        run: |
          dotnet run --urls=http://localhost:5128 &
          sleep 20  # Increase sleep time to ensure the app is fully started

      - name: Get container logs (for debugging)
        run: docker logs $(docker ps -q --filter ancestor=mcr.microsoft.com/dotnet/aspnet:7.0)

      - name: Run Playwright tests
        run: npx playwright test
